export const states = [
  {
    stateNumber: 1,
    state: "Alabama",
    capital: "Montgomery",
    population: 5024279,
    yearEstablished: 1819,
  },
  {
    stateNumber: 2,
    state: "Alaska",
    capital: "Juneau",
    population: 731545,
    yearEstablished: 1959,
  },
  {
    stateNumber: 3,
    state: "Arizona",
    capital: "Phoenix",
    population: 7151502,
    yearEstablished: 1912,
  },
  {
    stateNumber: 4,
    state: "Arkansas",
    capital: "Little Rock",
    population: 3017804,
    yearEstablished: 1836,
  },
  {
    stateNumber: 5,
    state: "California",
    capital: "Sacramento",
    population: 39538223,
    yearEstablished: 1850,
  },
  {
    stateNumber: 6,
    state: "Colorado",
    capital: "Denver",
    population: 5773714,
    yearEstablished: 1876,
  },
  {
    stateNumber: 7,
    state: "Connecticut",
    capital: "Hartford",
    population: 3605944,
    yearEstablished: 1788,
  },
  {
    stateNumber: 8,
    state: "Delaware",
    capital: "Dover",
    population: 989948,
    yearEstablished: 1787,
  },
  {
    stateNumber: 9,
    state: "Florida",
    capital: "Tallahassee",
    population: 21538187,
    yearEstablished: 1845,
  },
  {
    stateNumber: 10,
    state: "Georgia",
    capital: "Atlanta",
    population: 10519475,
    yearEstablished: 1788,
  },
  {
    stateNumber: 11,
    state: "Hawaii",
    capital: "Honolulu",
    population: 1455271,
    yearEstablished: 1959,
  },
  {
    stateNumber: 12,
    state: "Idaho",
    capital: "Boise",
    population: 1839106,
    yearEstablished: 1890,
  },
  {
    stateNumber: 13,
    state: "Illinois",
    capital: "Springfield",
    population: 12812508,
    yearEstablished: 1818,
  },
  {
    stateNumber: 14,
    state: "Indiana",
    capital: "Indianapolis",
    population: 6788010,
    yearEstablished: 1816,
  },
  {
    stateNumber: 15,
    state: "Iowa",
    capital: "Des Moines",
    population: 3190369,
    yearEstablished: 1846,
  },
  {
    stateNumber: 16,
    state: "Kansas",
    capital: "Topeka",
    population: 2913314,
    yearEstablished: 1861,
  },
  {
    stateNumber: 17,
    state: "Kentucky",
    capital: "Frankfort",
    population: 4505836,
    yearEstablished: 1792,
  },
  {
    stateNumber: 18,
    state: "Louisiana",
    capital: "Baton Rouge",
    population: 4657757,
    yearEstablished: 1812,
  },
  {
    stateNumber: 19,
    state: "Maine",
    capital: "Augusta",
    population: 1344212,
    yearEstablished: 1820,
  },
  {
    stateNumber: 20,
    state: "Maryland",
    capital: "Annapolis",
    population: 6177224,
    yearEstablished: 1788,
  },
  {
    stateNumber: 21,
    state: "Massachusetts",
    capital: "Boston",
    population: 7029917,
    yearEstablished: 1788,
  },
  {
    stateNumber: 22,
    state: "Michigan",
    capital: "Lansing",
    population: 10077331,
    yearEstablished: 1837,
  },
  {
    stateNumber: 23,
    state: "Minnesota",
    capital: "Saint Paul",
    population: 5706494,
    yearEstablished: 1849,
  },
  {
    stateNumber: 24,
    state: "Mississippi",
    capital: "Jackson",
    population: 2961279,
    yearEstablished: 1817,
  },
  {
    stateNumber: 25,
    state: "Missouri",
    capital: "Jefferson City",
    population: 6154913,
    yearEstablished: 1821,
  },
  {
    stateNumber: 26,
    state: "Montana",
    capital: "Helena",
    population: 1084225,
    yearEstablished: 1889,
  },
  {
    stateNumber: 27,
    state: "Nebraska",
    capital: "Lincoln",
    population: 1934408,
    yearEstablished: 1867,
  },
  {
    stateNumber: 28,
    state: "Nevada",
    capital: "Carson City",
    population: 3104614,
    yearEstablished: 1864,
  },
  {
    stateNumber: 29,
    state: "New Hampshire",
    capital: "Concord",
    population: 1377529,
    yearEstablished: 1788,
  },
  {
    stateNumber: 30,
    state: "New Jersey",
    capital: "Trenton",
    population: 9288994,
    yearEstablished: 1787,
  },
  {
    stateNumber: 31,
    state: "New Mexico",
    capital: "Santa Fe",
    population: 2117522,
    yearEstablished: 1912,
  },
  {
    stateNumber: 32,
    state: "New York",
    capital: "Albany",
    population: 20201249,
    yearEstablished: 1788,
  },
  {
    stateNumber: 33,
    state: "North Carolina",
    capital: "Raleigh",
    population: 10439388,
    yearEstablished: 1789,
  },
  {
    stateNumber: 34,
    state: "North Dakota",
    capital: "Bismarck",
    population: 779094,
    yearEstablished: 1889,
  },
  {
    stateNumber: 35,
    state: "Ohio",
    capital: "Columbus",
    population: 11799448,
    yearEstablished: 1803,
  },
  {
    stateNumber: 36,
    state: "Oklahoma",
    capital: "Oklahoma City",
    population: 3956971,
    yearEstablished: 1907,
  },
  {
    stateNumber: 37,
    state: "Oregon",
    capital: "Salem",
    population: 4237256,
    yearEstablished: 1859,
  },
  {
    stateNumber: 38,
    state: "Pennsylvania",
    capital: "Harrisburg",
    population: 13002700,
    yearEstablished: 1787,
  },
  {
    stateNumber: 39,
    state: "Rhode Island",
    capital: "Providence",
    population: 1097379,
    yearEstablished: 1790,
  },
  {
    stateNumber: 40,
    state: "South Carolina",
    capital: "Columbia",
    population: 5119440,
    yearEstablished: 1788,
  },
  {
    stateNumber: 41,
    state: "South Dakota",
    capital: "Pierre",
    population: 886667,
    yearEstablished: 1889,
  },
  {
    stateNumber: 42,
    state: "Tennessee",
    capital: "Nashville",
    population: 6910840,
    yearEstablished: 1796,
  },
  {
    stateNumber: 43,
    state: "Texas",
    capital: "Austin",
    population: 29145505,
    yearEstablished: 1845,
  },
  {
    stateNumber: 44,
    state: "Utah",
    capital: "Salt Lake City",
    population: 3271616,
    yearEstablished: 1896,
  },
  {
    stateNumber: 45,
    state: "Vermont",
    capital: "Montpelier",
    population: 643077,
    yearEstablished: 1791,
  },
  {
    stateNumber: 46,
    state: "Virginia",
    capital: "Richmond",
    population: 8631393,
    yearEstablished: 1788,
  },
  {
    stateNumber: 47,
    state: "Washington",
    capital: "Olympia",
    population: 7693612,
    yearEstablished: 1889,
  },
  {
    stateNumber: 48,
    state: "West Virginia",
    capital: "Charleston",
    population: 1792147,
    yearEstablished: 1863,
  },
  {
    stateNumber: 49,
    state: "Wisconsin",
    capital: "Madison",
    population: 5893718,
    yearEstablished: 1848,
  },
  {
    stateNumber: 50,
    state: "Wyoming",
    capital: "Cheyenne",
    population: 578759,
    yearEstablished: 1890,
  },
];
